id: P007122
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15463
  title: འབྲུག་གི་ཁྲིམས་གཞུང་།
  author: ''
  volumes:
    d5bcbc2a78014786884a7e4cf66a90a2:
      image_group_id: I1KG15474
      title: ''
      volume_number: 1
      total_pages: 192
    833d435d2ce64f45b7a8d302bf4f2827:
      image_group_id: I1KG15475
      title: ''
      volume_number: 2
      total_pages: 142
    f5b620377e5d408abe27bec96e2a3a99:
      image_group_id: I1KG15476
      title: ''
      volume_number: 3
      total_pages: 114
    98042bf1d35c4408a7967ebaecd63231:
      image_group_id: I1KG15477
      title: ''
      volume_number: 4
      total_pages: 134
    c37a24e7e5204229bdc1320d0c1d49f1:
      image_group_id: I1KG15478
      title: ''
      volume_number: 5
      total_pages: 160
    1878a09e7c3646ed96ea4025ec92abe9:
      image_group_id: I1KG15479
      title: ''
      volume_number: 6
      total_pages: 108
ebook_metadata:
  title: འབྲུག་གི་ཁྲིམས་གཞུང་།
  author: ''
  sku: P007122
  cover: cover.jpg
  layers:
  - pagination
