id: IF7971750
legacy_id: P007122
ocr_import_info:
  bdrc_scan_id: W1KG15463
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T20:50:24'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T08:20:05.608917+00:00'
last_modified: 2022-08-31 16:20:24.363418
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG15463
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG15463
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འབྲུག་གི་ཁྲིམས་གཞུང་།
statistics:
  ocr_word_mean_confidence_index: 0.8355889880445652
  ocr_word_median_confidence_index: 0.9100000262260437
quality: null
bases:
  I1KG15475:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15475
      total_pages: 142
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG15475.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8243814323642655
    legacy_id: v002
  I1KG15478:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15478
      total_pages: 160
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG15478.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8461629777477724
    legacy_id: v005
  I1KG15474:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15474
      total_pages: 192
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15474.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.8686617423199933
    legacy_id: v001
  I1KG15476:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15476
      total_pages: 114
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG15476.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.8364071977769245
    legacy_id: v003
  I1KG15477:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15477
      total_pages: 134
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG15477.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.824432206856269
    legacy_id: v004
  I1KG15479:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15479
      total_pages: 108
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG15479.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7894918891648188
    legacy_id: v006
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
