id: IF7971750
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:51:13+00:00'
last_modified: '2022-06-09T06:12:47.626621+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15463
  title: འབྲུག་གི་ཁྲིམས་གཞུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    1BA4:
      image_group_id: I1KG15474
      title: Volume 1 of 'brug gi khrims gzhung /
      total_pages: 192
      order: 1
      base_file: 1BA4.txt
    42D2:
      image_group_id: I1KG15475
      title: Volume 2 of 'brug gi khrims gzhung /
      total_pages: 142
      order: 2
      base_file: 42D2.txt
    0879:
      image_group_id: I1KG15476
      title: Volume 3 of 'brug gi khrims gzhung /
      total_pages: 114
      order: 3
      base_file: 0879.txt
    '2816':
      image_group_id: I1KG15477
      title: Volume 4 of 'brug gi khrims gzhung /
      total_pages: 134
      order: 4
      base_file: 2816.txt
    69A3:
      image_group_id: I1KG15478
      title: Volume 5 of 'brug gi khrims gzhung /
      total_pages: 160
      order: 5
      base_file: 69A3.txt
    2EF4:
      image_group_id: I1KG15479
      title: Volume 6 of 'brug gi khrims gzhung /
      total_pages: 108
      order: 6
      base_file: 2EF4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
